from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(543, 265)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.labelGOST = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelGOST.setFont(font)
        self.labelGOST.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelGOST.setMinimumSize(QtCore.QSize(250, 100))
        self.labelGOST.setObjectName("labelGOST")
        self.gridLayout.addWidget(self.labelGOST, 0, 2, 1, 7)
        self.labelQ1 = QtWidgets.QLabel(parent=Form)
        self.labelQ1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelQ1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelQ1.setObjectName("labelQ1")
        self.gridLayout.addWidget(self.labelQ1, 1, 3, 1, 1)
        self.labelQ2 = QtWidgets.QLabel(parent=Form)
        self.labelQ2.setMaximumSize(QtCore.QSize(50, 50))
        self.labelQ2.setObjectName("labelQ2")
        self.gridLayout.addWidget(self.labelQ2, 1, 4, 1, 1)
        self.labelP1 = QtWidgets.QLabel(parent=Form)
        self.labelP1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelP1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelP1.setObjectName("labelP1")
        self.gridLayout.addWidget(self.labelP1, 1, 5, 1, 1)
        self.labelP2 = QtWidgets.QLabel(parent=Form)
        self.labelP2.setMaximumSize(QtCore.QSize(50, 50))
        self.labelP2.setObjectName("labelP2")
        self.gridLayout.addWidget(self.labelP2, 1, 6, 1, 1)
        self.labelG1 = QtWidgets.QLabel(parent=Form)
        self.labelG1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelG1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelG1.setObjectName("labelG1")
        self.gridLayout.addWidget(self.labelG1, 1, 7, 1, 1)
        self.labelG2 = QtWidgets.QLabel(parent=Form)
        self.labelG2.setMaximumSize(QtCore.QSize(50, 50))
        self.labelG2.setObjectName("labelG2")
        self.gridLayout.addWidget(self.labelG2, 1, 8, 1, 1)
        self.labelX1 = QtWidgets.QLabel(parent=Form)
        self.labelX1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelX1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelX1.setObjectName("labelX1")
        self.gridLayout.addWidget(self.labelX1, 2, 3, 1, 1)
        self.labelX2 = QtWidgets.QLabel(parent=Form)
        self.labelX2.setMaximumSize(QtCore.QSize(50, 50))
        self.labelX2.setObjectName("labelX2")
        self.gridLayout.addWidget(self.labelX2, 2, 4, 1, 1)
        self.labelY1 = QtWidgets.QLabel(parent=Form)
        self.labelY1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelY1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelY1.setObjectName("labelY1")
        self.gridLayout.addWidget(self.labelY1, 2, 5, 1, 1)
        self.labelY2 = QtWidgets.QLabel(parent=Form)
        self.labelY2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelY2.setObjectName("labelY2")
        self.gridLayout.addWidget(self.labelY2, 2, 6, 1, 1)
        self.labelAnotherY1 = QtWidgets.QLabel(parent=Form)
        self.labelAnotherY1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelAnotherY1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelAnotherY1.setObjectName("labelAnotherY1")
        self.gridLayout.addWidget(self.labelAnotherY1, 3, 5, 1, 1)
        self.labelAnotherY2 = QtWidgets.QLabel(parent=Form)
        self.labelAnotherY2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelAnotherY2.setObjectName("labelAnotherY2")
        self.gridLayout.addWidget(self.labelAnotherY2, 3, 6, 1, 1)
        self.btnLoad = QtWidgets.QPushButton(parent=Form)
        self.btnLoad.setMaximumSize(QtCore.QSize(150, 30))
        self.btnLoad.setObjectName("btnLoad")
        self.gridLayout.addWidget(self.btnLoad, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 2, 1, 1)
        self.btnSel = QtWidgets.QPushButton(parent=Form)
        self.btnSel.setMaximumSize(QtCore.QSize(150, 30))
        self.btnSel.setObjectName("btnSel")
        self.gridLayout.addWidget(self.btnSel, 5, 2, 1, 1)
        self.btnSelEDS = QtWidgets.QPushButton(parent=Form)
        self.btnSelEDS.setMaximumSize(QtCore.QSize(150, 30))
        self.btnSelEDS.setObjectName("btnSelEDS")
        self.gridLayout.addWidget(self.btnSelEDS, 6, 2, 1, 1)
        self.btnDec = QtWidgets.QPushButton(parent=Form)
        self.btnDec.setMaximumSize(QtCore.QSize(150, 30))
        self.btnDec.setObjectName("btnDec")
        self.gridLayout.addWidget(self.btnDec, 7, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 9, 1, 1)
        self.labelEDS1 = QtWidgets.QLabel(parent=Form)
        self.labelEDS1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelEDS1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelEDS1.setObjectName("labelEDS1")
        self.gridLayout.addWidget(self.labelEDS1, 6, 3, 1, 1)
        self.labelEDS2 = QtWidgets.QLabel(parent=Form)
        self.labelEDS2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelEDS2.setObjectName("labelEDS2")
        self.gridLayout.addWidget(self.labelEDS2, 6, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Decryption"))
        self.labelGOST.setText(_translate("Form", "Расшифрование по алгоритму ГОСТ 34.10-94"))
        self.labelQ1.setText(_translate("Form", "Число q:"))
        self.labelQ2.setText(_translate("Form", "num"))
        self.labelP1.setText(_translate("Form", "Число p:"))
        self.labelP2.setText(_translate("Form", "num"))
        self.labelG1.setText(_translate("Form", "Число g:"))
        self.labelG2.setText(_translate("Form", "num"))
        self.labelX1.setText(_translate("Form", "Число x:"))
        self.labelX2.setText(_translate("Form", "num"))
        self.labelY1.setText(_translate("Form", "Число y:"))
        self.labelY2.setText(_translate("Form", "num"))
        self.labelAnotherY1.setText(_translate("Form", "Другой y:"))
        self.labelAnotherY2.setText(_translate("Form", "num"))
        self.btnLoad.setText(_translate("Form", "Загрузить числа"))
        self.btnSel.setText(_translate("Form", "Выбрать файл"))
        self.btnSelEDS.setText(_translate("Form", "Выбрать ЭЦП"))
        self.btnDec.setText(_translate("Form", "Проверить ЭЦП"))
        self.labelEDS1.setText(_translate("Form", "ЭЦП:"))
        self.labelEDS2.setText(_translate("Form", "num"))
