from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(758, 540)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelMainName = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelMainName.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelMainName.setFont(font)
        self.labelMainName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelMainName.setObjectName("labelMainName")
        self.gridLayout.addWidget(self.labelMainName, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignJustify)
        self.btnEnc1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEnc1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEnc1.sizePolicy().hasHeightForWidth())
        self.btnEnc1.setSizePolicy(sizePolicy)
        self.btnEnc1.setMaximumSize(QtCore.QSize(250, 50))
        self.btnEnc1.setMinimumSize(QtCore.QSize(150, 25))
        self.btnEnc1.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnEnc1.setBaseSize(QtCore.QSize(0, 0))
        self.btnEnc1.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btnEnc1.setObjectName("btnEnc1")
        self.gridLayout.addWidget(self.btnEnc1, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignJustify)
        self.btnEnc2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEnc2.setMaximumSize(QtCore.QSize(250, 50))
        self.btnEnc2.setMinimumSize(QtCore.QSize(150, 25))
        self.btnEnc2.setObjectName("btnEnc2")
        self.gridLayout.addWidget(self.btnEnc2, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignJustify)
        self.btnEnc3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEnc3.setMaximumSize(QtCore.QSize(250, 50))
        self.btnEnc3.setMinimumSize(QtCore.QSize(150, 25))
        self.btnEnc3.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnEnc3.setObjectName("btnEnc3")
        self.gridLayout.addWidget(self.btnEnc3, 3, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignJustify)
        self.btnEnc4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEnc4.setMaximumSize(QtCore.QSize(250, 50))
        self.btnEnc4.setMinimumSize(QtCore.QSize(150, 25))
        self.btnEnc4.setObjectName("btnEnc4")
        self.gridLayout.addWidget(self.btnEnc4, 4, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignJustify)
        self.labelNone = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelNone.setText("")
        self.labelNone.setObjectName("labelNone")
        self.gridLayout.addWidget(self.labelNone, 5, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignJustify)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Crypto"))
        self.labelMainName.setText(_translate("MainWindow", "Выберите метод шифрования"))
        self.btnEnc1.setText(_translate("MainWindow", "RSA"))
        self.btnEnc2.setText(_translate("MainWindow", "EGSA"))
        self.btnEnc3.setText(_translate("MainWindow", "DSA"))
        self.btnEnc4.setText(_translate("MainWindow", "ГОСТ 34.10-94"))
