from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(543, 265)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.labelQ1 = QtWidgets.QLabel(parent=Form)
        self.labelQ1.setMaximumSize(QtCore.QSize(50, 50))
        self.labelQ1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelQ1.setObjectName("labelQ1")
        self.gridLayout.addWidget(self.labelQ1, 1, 5, 1, 1)
        self.labelP2 = QtWidgets.QLabel(parent=Form)
        self.labelP2.setMaximumSize(QtCore.QSize(50, 50))
        self.labelP2.setObjectName("labelP2")
        self.gridLayout.addWidget(self.labelP2, 1, 4, 1, 1)
        self.labelE1 = QtWidgets.QLabel(parent=Form)
        self.labelE1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelE1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelE1.setObjectName("labelE1")
        self.gridLayout.addWidget(self.labelE1, 3, 3, 1, 1)
        self.labelN2 = QtWidgets.QLabel(parent=Form)
        self.labelN2.setMaximumSize(QtCore.QSize(50, 50))
        self.labelN2.setObjectName("labelN2")
        self.gridLayout.addWidget(self.labelN2, 2, 4, 1, 1)
        self.btnPQ = QtWidgets.QPushButton(parent=Form)
        self.btnPQ.setMaximumSize(QtCore.QSize(150, 30))
        self.btnPQ.setObjectName("btnPQ")
        self.gridLayout.addWidget(self.btnPQ, 1, 2, 1, 1)
        self.btnSave = QtWidgets.QPushButton(parent=Form)
        self.btnSave.setMaximumSize(QtCore.QSize(150, 30))
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 2, 2, 1, 1)
        self.btnE = QtWidgets.QPushButton(parent=Form)
        self.btnE.setMaximumSize(QtCore.QSize(150, 30))
        self.btnE.setObjectName("btnE")
        self.gridLayout.addWidget(self.btnE, 3, 2, 1, 1)
        self.btnSel = QtWidgets.QPushButton(parent=Form)
        self.btnSel.setMaximumSize(QtCore.QSize(150, 30))
        self.btnSel.setObjectName("btnSel")
        self.gridLayout.addWidget(self.btnSel, 5, 2, 1, 1)
        self.btnEnc = QtWidgets.QPushButton(parent=Form)
        self.btnEnc.setMaximumSize(QtCore.QSize(150, 30))
        self.btnEnc.setObjectName("btnEnc")
        self.gridLayout.addWidget(self.btnEnc, 8, 3, 1, 1)
        self.btnSaveEDS = QtWidgets.QPushButton(parent=Form)
        self.btnSaveEDS.setMaximumSize(QtCore.QSize(150, 30))
        self.btnSaveEDS.setObjectName("btnSaveEDS")
        self.gridLayout.addWidget(self.btnSaveEDS, 9, 3, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.labelFN1 = QtWidgets.QLabel(parent=Form)
        self.labelFN1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelFN1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelFN1.setObjectName("labelFN1")
        self.gridLayout.addWidget(self.labelFN1, 2, 5, 1, 1)
        self.labelFN2 = QtWidgets.QLabel(parent=Form)
        self.labelFN2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelFN2.setObjectName("labelFN2")
        self.gridLayout.addWidget(self.labelFN2, 2, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 10, 3, 1, 1)
        self.labelRSA = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelRSA.setFont(font)
        self.labelRSA.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelRSA.setMinimumSize(QtCore.QSize(250, 100))
        self.labelRSA.setObjectName("labelRSA")
        self.gridLayout.addWidget(self.labelRSA, 0, 2, 1, 5)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 9, 1, 1)
        self.labelQ2 = QtWidgets.QLabel(parent=Form)
        self.labelQ2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelQ2.setObjectName("labelQ2")
        self.gridLayout.addWidget(self.labelQ2, 1, 6, 1, 1)
        self.labelP1 = QtWidgets.QLabel(parent=Form)
        self.labelP1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelP1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelP1.setObjectName("labelP1")
        self.gridLayout.addWidget(self.labelP1, 1, 3, 1, 1)
        self.labelN1 = QtWidgets.QLabel(parent=Form)
        self.labelN1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelN1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelN1.setObjectName("labelN1")
        self.gridLayout.addWidget(self.labelN1, 2, 3, 1, 1)
        self.labelE2 = QtWidgets.QLabel(parent=Form)
        self.labelE2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelE2.setObjectName("labelE2")
        self.gridLayout.addWidget(self.labelE2, 3, 4, 1, 1)
        self.labelD1 = QtWidgets.QLabel(parent=Form)
        self.labelD1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelD1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelD1.setObjectName("labelD1")
        self.gridLayout.addWidget(self.labelD1, 3, 5, 1, 1)
        self.labelD2 = QtWidgets.QLabel(parent=Form)
        self.labelD2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelD2.setObjectName("labelD2")
        self.gridLayout.addWidget(self.labelD2, 3, 6, 1, 1)
        self.labelAnotherE1 = QtWidgets.QLabel(parent=Form)
        self.labelAnotherE1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelAnotherE1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelAnotherE1.setObjectName("labelAnotherE1")
        self.gridLayout.addWidget(self.labelAnotherE1, 4, 3, 1, 1)
        self.labelAnotherE2 = QtWidgets.QLabel(parent=Form)
        self.labelAnotherE2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelAnotherE2.setObjectName("labelAnotherE2")
        self.gridLayout.addWidget(self.labelAnotherE2, 4, 4, 1, 1)
        self.labelHash1 = QtWidgets.QLabel(parent=Form)
        self.labelHash1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelHash1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelHash1.setObjectName("labelHash1")
        self.gridLayout.addWidget(self.labelHash1, 6, 2, 1, 1)
        self.labelHash2 = QtWidgets.QLabel(parent=Form)
        self.labelHash2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelHash2.setObjectName("labelHash2")
        self.gridLayout.addWidget(self.labelHash2, 6, 3, 1, 1)
        self.labelC1 = QtWidgets.QLabel(parent=Form)
        self.labelC1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelC1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelC1.setObjectName("labelC1")
        self.gridLayout.addWidget(self.labelC1, 6, 5, 1, 1)
        self.labelC2 = QtWidgets.QLabel(parent=Form)
        self.labelC2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelC2.setObjectName("labelC2")
        self.gridLayout.addWidget(self.labelC2, 6, 6, 1, 1)
        self.labelEDS1 = QtWidgets.QLabel(parent=Form)
        self.labelEDS1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelEDS1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelEDS1.setObjectName("labelEDS1")
        self.gridLayout.addWidget(self.labelEDS1, 9, 4, 1, 1)
        self.labelEDS2 = QtWidgets.QLabel(parent=Form)
        self.labelEDS2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelEDS2.setObjectName("labelEDS2")
        self.gridLayout.addWidget(self.labelEDS2, 9, 5, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Encryption"))
        self.labelQ1.setText(_translate("Form", "Число q:"))
        self.labelP2.setText(_translate("Form", "num"))
        self.labelE1.setText(_translate("Form", "Число e:"))
        self.labelN2.setText(_translate("Form", "num"))
        self.btnPQ.setText(_translate("Form", "Получить числа"))
        self.btnSave.setText(_translate("Form", "Сохранить числа"))
        self.btnE.setText(_translate("Form", "Выбрать e"))
        self.btnSel.setText(_translate("Form", "Выбрать файл"))
        self.btnEnc.setText(_translate("Form", "Зашифровать"))
        self.btnSaveEDS.setText(_translate("Form", "Сохранить ЭЦП"))
        self.labelFN1.setText(_translate("Form", "Число f(n):"))
        self.labelFN2.setText(_translate("Form", "num"))
        self.labelRSA.setText(_translate("Form", "Шифрование по алгоритму RSA"))
        self.labelQ2.setText(_translate("Form", "num"))
        self.labelP1.setText(_translate("Form", "Число p:"))
        self.labelN1.setText(_translate("Form", "Число n:"))
        self.labelE2.setText(_translate("Form", "num"))
        self.labelD1.setText(_translate("Form", "Число d:"))
        self.labelD2.setText(_translate("Form", "num"))
        self.labelAnotherE1.setText(_translate("Form", "Другое e:"))
        self.labelAnotherE2.setText(_translate("Form", "num"))
        self.labelHash1.setText(_translate("Form", "Hash:"))
        self.labelHash2.setText(_translate("Form", "num"))
        self.labelC1.setText(_translate("Form", "Число c:"))
        self.labelC2.setText(_translate("Form", "num"))
        self.labelEDS1.setText(_translate("Form", "ЭЦП:"))
        self.labelEDS2.setText(_translate("Form", "num"))
