from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(586, 421)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 6, 1, 1)
        self.labelFN1 = QtWidgets.QLabel(parent=Form)
        self.labelFN1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelFN1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelFN1.setObjectName("labelFN1")
        self.gridLayout.addWidget(self.labelFN1, 2, 4, 1, 1)
        self.labelP2 = QtWidgets.QLabel(parent=Form)
        self.labelP2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelP2.setObjectName("labelP2")
        self.gridLayout.addWidget(self.labelP2, 1, 3, 1, 1)
        self.labelFN2 = QtWidgets.QLabel(parent=Form)
        self.labelFN2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelFN2.setObjectName("labelFN2")
        self.gridLayout.addWidget(self.labelFN2, 2, 5, 1, 1)
        self.labelP1 = QtWidgets.QLabel(parent=Form)
        self.labelP1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelP1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelP1.setObjectName("labelP1")
        self.gridLayout.addWidget(self.labelP1, 1, 2, 1, 1)
        self.labelE1 = QtWidgets.QLabel(parent=Form)
        self.labelE1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelE1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelE1.setObjectName("labelE1")
        self.gridLayout.addWidget(self.labelE1, 3, 2, 1, 1)
        self.labelN1 = QtWidgets.QLabel(parent=Form)
        self.labelN1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelN1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelN1.setObjectName("labelN1")
        self.gridLayout.addWidget(self.labelN1, 2, 2, 1, 1)
        self.labelD1 = QtWidgets.QLabel(parent=Form)
        self.labelD1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelD1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelD1.setObjectName("labelD1")
        self.gridLayout.addWidget(self.labelD1, 3, 4, 1, 1)
        self.labelQ1 = QtWidgets.QLabel(parent=Form)
        self.labelQ1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelQ1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelQ1.setObjectName("labelQ1")
        self.gridLayout.addWidget(self.labelQ1, 1, 4, 1, 1)
        self.labelQ2 = QtWidgets.QLabel(parent=Form)
        self.labelQ2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelQ2.setObjectName("labelQ2")
        self.gridLayout.addWidget(self.labelQ2, 1, 5, 1, 1)
        self.labelN2 = QtWidgets.QLabel(parent=Form)
        self.labelN2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelN2.setObjectName("labelN2")
        self.gridLayout.addWidget(self.labelN2, 2, 3, 1, 1)
        self.labelE2 = QtWidgets.QLabel(parent=Form)
        self.labelE2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelE2.setObjectName("labelE2")
        self.gridLayout.addWidget(self.labelE2, 3, 3, 1, 1)
        self.btnLoadNum = QtWidgets.QPushButton(parent=Form)
        self.btnLoadNum.setMaximumSize(QtCore.QSize(150, 30))
        self.btnLoadNum.setObjectName("btnLoadNum")
        self.gridLayout.addWidget(self.btnLoadNum, 1, 1, 1, 1)
        self.btnSelE = QtWidgets.QPushButton(parent=Form)
        self.btnSelE.setMaximumSize(QtCore.QSize(150, 30))
        self.btnSelE.setObjectName("btnSelE")
        self.gridLayout.addWidget(self.btnSelE, 2, 1, 1, 1)
        self.btnSelEDS = QtWidgets.QPushButton(parent=Form)
        self.btnSelEDS.setMaximumSize(QtCore.QSize(150, 30))
        self.btnSelEDS.setObjectName("btnSelEDS")
        self.gridLayout.addWidget(self.btnSelEDS, 6, 1, 1, 1)
        self.btnSelEnc = QtWidgets.QPushButton(parent=Form)
        self.btnSelEnc.setMaximumSize(QtCore.QSize(150, 30))
        self.btnSelEnc.setObjectName("btnSelEnc")
        self.gridLayout.addWidget(self.btnSelEnc, 5, 1, 1, 1)
        self.labelEDS1 = QtWidgets.QLabel(parent=Form)
        self.labelEDS1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelEDS1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelEDS1.setObjectName("labelEDS1")
        self.gridLayout.addWidget(self.labelEDS1, 6, 2, 1, 1)
        self.labelEDS2 = QtWidgets.QLabel(parent=Form)
        self.labelEDS2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelEDS2.setObjectName("labelEDS2")
        self.gridLayout.addWidget(self.labelEDS2, 6, 3, 1, 1)
        self.labelC1 = QtWidgets.QLabel(parent=Form)
        self.labelC1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelC1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelC1.setObjectName("labelC1")
        self.gridLayout.addWidget(self.labelC1, 6, 4, 1, 1)
        self.labelC2 = QtWidgets.QLabel(parent=Form)
        self.labelC2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelC2.setObjectName("labelC2")
        self.gridLayout.addWidget(self.labelC2, 6, 5, 1, 1)
        self.btnDec = QtWidgets.QPushButton(parent=Form)
        self.btnDec.setMaximumSize(QtCore.QSize(150, 50))
        self.btnDec.setObjectName("btnDec")
        self.gridLayout.addWidget(self.btnDec, 7, 1, 1, 1)
        self.labelD2 = QtWidgets.QLabel(parent=Form)
        self.labelD2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelD2.setObjectName("labelD2")
        self.gridLayout.addWidget(self.labelD2, 3, 5, 1, 1)
        self.labelAnotherE1 = QtWidgets.QLabel(parent=Form)
        self.labelAnotherE1.setMaximumSize(QtCore.QSize(150, 50))
        self.labelAnotherE1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelAnotherE1.setObjectName("labelAnotherE1")
        self.gridLayout.addWidget(self.labelAnotherE1, 4, 2, 1, 1)
        self.labelAnotherE2 = QtWidgets.QLabel(parent=Form)
        self.labelAnotherE2.setMaximumSize(QtCore.QSize(150, 50))
        self.labelAnotherE2.setObjectName("labelAnotherE2")
        self.gridLayout.addWidget(self.labelAnotherE2, 4, 3, 1, 1)
        self.labelRSADec = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelRSADec.setFont(font)
        self.labelRSADec.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelRSADec.setMinimumSize(QtCore.QSize(250, 100))
        self.labelRSADec.setObjectName("labelRSADec")
        self.gridLayout.addWidget(self.labelRSADec, 0, 1, 1, 5)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Decryption"))
        self.labelFN1.setText(_translate("Form", "Число f(n):"))
        self.labelP2.setText(_translate("Form", "num"))
        self.labelFN2.setText(_translate("Form", "num"))
        self.labelP1.setText(_translate("Form", "Число p:"))
        self.labelE1.setText(_translate("Form", "Число e:"))
        self.labelN1.setText(_translate("Form", "Число n:"))
        self.labelD1.setText(_translate("Form", "Число d:"))
        self.labelQ1.setText(_translate("Form", "Число q:"))
        self.labelQ2.setText(_translate("Form", "num"))
        self.labelN2.setText(_translate("Form", "num"))
        self.labelE2.setText(_translate("Form", "num"))
        self.labelEDS1.setText(_translate("Form", "ЭЦП:"))
        self.labelEDS2.setText(_translate("Form", "num"))
        self.labelC1.setText(_translate("Form", "Число c:"))
        self.labelC2.setText(_translate("Form", "num"))
        self.labelAnotherE1.setText(_translate("Form", "Другое e:"))
        self.labelAnotherE2.setText(_translate("Form", "num"))
        self.btnLoadNum.setText(_translate("Form", "Загрузить числа"))
        self.btnSelE.setText(_translate("Form", "Сохранить e"))
        self.btnSelEnc.setText(_translate("Form", "Выбрать файл"))
        self.btnSelEDS.setText(_translate("Form", "Выбрать ЭЦП"))
        self.btnDec.setText(_translate("Form", "Расшифровать"))
        self.labelD2.setText(_translate("Form", "num"))
        self.labelRSADec.setText(_translate("Form", "Расшифрование по алгоритму RSA"))
